spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://localhost:5432/taskTk
    username: postgres
    password: Alinogy7

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5002
